# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Log4perl-Layout-XMLLayout
version:      0.03
version_from: lib/Log/Log4perl/Layout/XMLLayout.pm
installdirs:  site
requires:
    Log::Log4perl:                 0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
